### ISSUE TITLE
-r seems to break it?

### ISSUE THREAD

**Issue by mattdesl** [hughsk/disc#20]
With `-r ./foo/bar:foo` option to browserify, I'm getting this error:

``` js
/usr/local/lib/node_modules/disc/bin/discify:59
    if (err) throw err
                   ^
Error: Unable to compile one of the supplied bundles!
    at /usr/local/lib/node_modules/disc/index.js:47:56
    at Array.map (native)
    at json (/usr/local/lib/node_modules/disc/index.js:46:5)
    at Function.bundle (/usr/local/lib/node_modules/disc/index.js:128:10)
    at handle (/usr/local/lib/node_modules/disc/bin/discify:56:8)
    at BufferList.disc.bundle.mode [as _callback] (/usr/local/lib/node_modules/disc/bin/discify:45:5)
    at BufferList.end (/usr/local/lib/node_modules/disc/node_modules/bl/bl.js:75:10)
    at Socket.onend (stream.js:79:10)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
```

Will try to look into it further..

EDIT: Seems related to browser-unpack; the latest version `1.0.0` fixes the problem but introduces another:

``` js
/projects/disc/node_modules/commondir/index.js:15
            throw new Error('relative path without a basedir');
                  ^
Error: relative path without a basedir
    at /projects/disc/node_modules/commondir/index.js:15:19
    at Array.reduce (native)
    at module.exports (/projects/disc/node_modules/commondir/index.js:13:30)
    at json (/projects/disc/index.js:70:14)
    at Function.bundle (/projects/disc/index.js:128:10)
    at handle (/projects/disc/bin/discify:56:8)
    at BufferList.disc.bundle.mode [as _callback] (/projects/disc/bin/discify:45:5)
    at BufferList.end (/projects/disc/node_modules/bl/bl.js:75:10)
    at Socket.onend (stream.js:79:10)
    at Socket.emit (events.js:117:20)
```

Using a full path for my `-r` option doesn't fix the issue.

**Comment by jackwanders** [comment]
Thought I'd add that this appears to continue to be an issue. I get the same error when creating a 'vendor' bundle that consists solely of `--require`'d modules, e.g.

```bash
$ browserify -r foo -r bar -r baz --full-paths > vendor.js
```

**Comment by jwhitfieldseed** [comment]
I'm getting the same issue with `--require` -only bundles.

**Comment by dominataa** [comment]
+1 cant compile with --require

**Comment by SystemParadox** [comment]
See also #41. Should be fixed by #45.
