### ISSUE TITLE
Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by Sinewyk** [hughsk/disc#24]
When i try verbatim what you said in your example since v1.0.0

```
browserify --full-paths index.js > bundle.js
discify bundle.js > disc.html
open disc.html
```

I get this

```
E:\Prog\front-web\node_modules\disc\index.js:100
        size: row.source.length
                 ^
TypeError: Cannot read property 'source' of undefined
    at tree.name (E:\Prog\front-web\node_modules\disc\index.js:100:18)
    at flat.unflatten.delimiter (E:\Prog\front-web\node_modules\disc\node_modules\file-tree\index.js:15:5)
    at next (E:\Prog\front-web\node_modules\disc\node_modules\file-tree\node_modules\async-reduce\index.js:11:7)
    at reduce (E:\Prog\front-web\node_modules\disc\node_modules\file-tree\node_modules\async-reduce\index.js:23:3)
    at tree (E:\Prog\front-web\node_modules\disc\node_modules\file-tree\index.js:13:3)
    at json (E:\Prog\front-web\node_modules\disc\index.js:94:3)
    at Function.bundle (E:\Prog\front-web\node_modules\disc\index.js:130:10)
    at handle (E:\Prog\front-web\node_modules\disc\bin\discify:56:8)
    at disc.bundle.mode (E:\Prog\front-web\node_modules\disc\bin\discify:51:5)
    at handler (E:\Prog\front-web\node_modules\disc\node_modules\map-async\index.js:36:29)
```

```var row = byid[id]``` is the culprit

id was correctly the entry file at first, but it seems that he still didn't found the data inside byid, i'll try some Object.keys on byid to check what happened after I eat something.

any ideas on your side ?

**Comment by cowwoc** [comment]
@Sinewyk I am running into the same problem. Did you open a bug report with Browserify? If so, where?

**Comment by Sinewyk** [comment]
Oh my bad. I bypassed the problem. I had a "classic" browserify workflow with all my custom things that worked. And then I simply run disc on the result file with --open.

Exactly like that (for example with gulp, but you can do that with anything really).

```javascript
gulp.task('deps-tree', ['browserify'], function() {
    var discSpawn = spawn('./node_modules/.bin/discify', ['./app/assets/scripts/bundle.js', '--open']);

    discSpawn.on('close', function() {
        process.exit(0);
    });
});
```

don't forget to send fullPaths: true as option inside the browserify command.
