### ISSUE TITLE
TypeError: Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by cowwoc** [hughsk/disc#29]
Given:

```
var source = require("vinyl-source-stream");
var disc = require("disc");
var javascript = new browserify(
{
	fullPaths: true
});

javascript.add(
[
	"./inDir/Index.js"
]);

javascript.
bundle().
pipe(source("Common.js")).
pipe(gulp.dest("./outDir"));
```

The above code works, but if I add `pipe(disc()).` between `source()` and `gulp.dest()` I get this exception:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Invalid non-string/buffer chunk
    at validChunk (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\bl\node_modules\readable-stream\lib\_stream_writable.js:164:14)
    at BufferList.Writable.write (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\bl\node_modules\readable-stream\lib\_stream_writable.js:193:12)
    at Stream.method [as write] (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\duplexer\index.js:47:39)
    at write (C:\Users\Gili\Documents\realestate\frontend\node_modules\vinyl-source-stream\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\Gili\Documents\realestate\frontend\node_modules\vinyl-source-stream\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\Gili\Documents\realestate\frontend\node_modules\vinyl-source-stream\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (C:\Users\Gili\Documents\realestate\frontend\node_modules\vinyl-source-stream\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\Gili\Documents\realestate\frontend\node_modules\vinyl-source-stream\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\Users\Gili\Documents\realestate\frontend\node_modules\vinyl-source-stream\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
```

Any ideas?

**Comment by hughsk** [comment]
Your streams are in the wrong order :)

Disc uses Node streams, not gulp/vinyl streams, so it takes input directly from browserify and needs to use `vinyl-source-stream` to make it work with gulp. The code above should actually be:

``` js
var browserify = require('browserify')
var disc = require('disc')
var javascript = browserify({
  fullPaths: true
})

javascript.add('./inDir/index.js')
javascript.bundle()
  .pipe(disc())
  .pipe(source('disc.html'))
  .pipe(gulp.dest('./outDir'))
```
