### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by cowwoc** [hughsk/disc#30]
This issue is not a duplicate of https://github.com/hughsk/disc/issues/24 (same title, different use-case).

1. Run the gulp code found at https://github.com/hughsk/disc/issues/29#issuecomment-71417368 but replace source path (passed into `add()`) and output path (passed into `dest()`) with an absolute path.
2. Exception is thrown:

```
C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\index.js:99
        size: row.source.length
                 ^
TypeError: Cannot read property 'source' of undefined
    at tree.name (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\index.js:99:18)
    at flat.unflatten.delimiter (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\file-tree\index.js:15:5)
    at next (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\file-tree\node_modules\async-reduce\index.js:11:7)
    at reduce (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\file-tree\node_modules\async-reduce\index.js:23:3)
    at tree (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\file-tree\index.js:13:3)
    at json (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\index.js:95:3)
    at bundle (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\index.js:129:10)
    at BufferList._callback (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\index.js:27:5)
    at BufferList.end (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\bl\bl.js:75:10)
    at Stream.method [as end] (C:\Users\Gili\Documents\realestate\frontend\node_modules\disc\node_modules\duplexer\index.js:47:39)
```

This issue is 100% reproducible.

**Comment by hughsk** [comment]
@cowwoc could you please include the bundled output from browserify that's breaking here? I need to be able to reproduce it on my machine to be able to help with this one.

**Comment by cowwoc** [comment]
@hughsk Please email me at cowwoc@bbs.darktech.org and I'll send you the bundle privately.

**Comment by GalCohen** [comment]
got the same issue here too

**Comment by t128** [comment]
here too :(

**Comment by formula1** [comment]
If you are on windows, you will likely need to do a `path.normalize(__dirname+"/path/to/file)` when creating your bundle.

It seems as though browserify doesn't do it for you : /

A working Example (for me):

```
function(req,res){
  browserify({
    fullPaths: true
  })
  .add(path.normalize(__dirname+"/browser.js"))
  .ignore("prompt")
  .transform({
    global: true
  }, 'uglifyify')
  .bundle().pipe(disc()).pipe(res);
}
```

Btw, if theres ever an issue with file loading and you're on windows:

* Make sure you use `path.normalize` any paths you will require
* consider installing ubuntu or a linux distro
* [Read this again](http://blogs.msdn.com/b/larryosterman/archive/2005/06/24/432386.aspx) to not get filled with hatred and hopelessness

**Comment by nemo** [comment]
This still happens to me even after using `fullPaths: true`, but only when I generate the bundle through gulp. Using command line works just fine.

Here's the gulp task:

```
var gulp = require('gulp');
var config   = require('../config');
var browserify = require('browserify');
var open = require('opener');
var disc = require('disc');
var fs = require('fs');


gulp.task('build:disc', function() {
    var output = config.destDirectory + '/disc.html';

    var bundler = browserify(config.sourceDirectory + '/' + config.sourceEntry, {
      fullPaths: true
    });

    bundler.bundle()
      .pipe(disc())
      .pipe(fs.createWriteStream(output))
      .once('close', function() {
        open(output);
      });

});
```

**Comment by formula1** [comment]
@nemo are you on windows?

**Comment by nemo** [comment]
@formula1 Nope - OSX>

**Comment by formula1** [comment]
What is the value of config.souceDirectory + "/" config.sourceEntry? I've been able to get this running on multiple systems so I was hoping it was a windows only issue

**Comment by nemo** [comment]
Here's how config is defined:

```javascript
var config = {};

config.destDirectory = "./dist";
config.sourceDirectory = "./app";
config.sourceEntry = 'index.js';
```

And in case it's helpful, here's the versions for what I'm using:

```json
{
    "browserify": "^9.0.7",
    "disc": "^1.3.2",
    "gulp": "^3.8.11",
    "opener": "^1.4.1"
}
```

**Comment by formula1** [comment]
`./Anything` is a relative path similar to `../something/above`. So when you specify the `{fullPaths:true}` What your implicitly saying is here is a direct path from point A to point B without taking advantage of the cwd. so instead of `./dist` you'll want `__dirname+"/dist"` This will result in something like `/home/name/something/else/path/to/your/file`.


I'm sorry if that is confusing, not sure the best way to explain.

**Comment by cheton** [comment]
In [index.js](https://github.com/hughsk/disc/blob/master/index.js#L90), you can resolve `mod.id` to an absolute path if it is a relative path.
For example:
```javascript
  var byid = modules.reduce(function(memo, mod) {
    var id = (function(id) {
      if (path.resolve(id) !== path.normalize(id)) { // check for relative path
        return path.resolve(process.cwd(), id); // resolves "id" to an absolute path
      }
      return id;
    }(mod.id));
    memo[id] = mod;
    return memo
  }, {})
```

I'm not sure if above code example may cause any side effects, but it did fix my issue even if using a relative path.

**Comment by nemo** [comment]
Ah I see. Yeah, using `__dirname` and `path.normalize` fixed the problem for me :)

**Comment by formula1** [comment]
You probably don't need normslize btw, that's usually a windows issue. Mac and Linux can generally path as freely as they like so long as the code base isn't going to be shared to windows

**Comment by nemo** [comment]
Without `path.normalize`, the error kept showing up on OS X because I had relative paths based on the `__dirname` in there. (`__dirname + "/../../index.js"` etc.)

**Comment by formula1** [comment]
Ah, makes sense.

**Comment by JorritPosthuma** [comment]
With cheton's patch, it also fixed it in our setup!

**Comment by jedverity** [comment]
@cheton patch worked for me too
