### ISSUE TITLE
module not resolving when using disc

### ISSUE THREAD

**Issue by kumavis** [hughsk/disc#32]
```
╭─{👳 } kumavis in ~/Development/Node/vapor/app on (master✱) 
╰─± browserify --full-paths index.js > bundle.js
╭─{👳 } kumavis in ~/Development/Node/vapor/app on (master✱) 
╰─± discify bundle.js > disc.html               

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Cannot find module '../mercury.js'
    at /usr/local/share/npm/lib/node_modules/disc/node_modules/module-deps/node_modules/browser-resolve/node_modules/resolve/lib/async.js:37:25
    at load (/usr/local/share/npm/lib/node_modules/disc/node_modules/module-deps/node_modules/browser-resolve/node_modules/resolve/lib/async.js:54:43)
    at /usr/local/share/npm/lib/node_modules/disc/node_modules/module-deps/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:22
    at /usr/local/share/npm/lib/node_modules/disc/node_modules/module-deps/node_modules/browser-resolve/node_modules/resolve/lib/async.js:16:47
    at Object.oncomplete (fs.js:108:15)
╭─{👳 } kumavis in ~/Development/Node/vapor/app on (master✱) 
╰─± browserify -v                               
9.0.3
```

**Comment by kumavis** [comment]
As you can see, the browserify build itself works correctly. not sure what the problem is.

**Comment by kumavis** [comment]
/usr/local/lib
└── disc@1.3.2
