### ISSUE TITLE
error "Duplicate data property in object literal not allowed in strict mode"

### ISSUE THREAD

**Issue by crobinson42** [hughsk/disc#53]
May be related to #51 ... Getting this error on cli command `discify bundle.js > disc.html`

```
Corys-MBP:~/projects/therms/.tmp/public/js (records)$ discify bundle.js > disc.html
/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:6268
            throw e;
            ^

Error: Line 10375: Duplicate data property in object literal not allowed in strict mode
    at throwError (/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:2159:21)
    at throwErrorTolerant (/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:2171:24)
    at parseObjectInitialiser (/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:2531:25)
    at /usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:5832:38
    at parsePrimaryExpression (/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:2657:20)
    at /usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:5832:38
    at trackLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:5732:61)
    at parsePostfixExpression (/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:2795:20)
    at /usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:5832:38
    at parseUnaryExpression (/usr/local/lib/node_modules/disc/node_modules/browser-unpack/node_modules/esprima-fb/esprima.js:2859:16)
```

**Comment by menonsamir** [comment]
+1
